# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x10org.example.grpc\"\x07\n\x05\x45mpty\"#\n\x11PublicKeyResponse\x12\x0e\n\x06pemKey\x18\x01 \x01(\x0c\"\'\n\x11SessionKeyRequest\x12\x12\n\nwrappedKey\x18\x01 \x01(\x0c\"4\n\x0f\x45ncryptedPacket\x12\n\n\x02iv\x18\x01 \x01(\x0c\x12\x15\n\rencryptedData\x18\x02 \x01(\x0c\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xcd\x01\n\nFlightData\x12\x10\n\x08\x66lightNo\x18\x01 \x01(\t\x12\x13\n\x0b\x61irlineName\x18\x02 \x01(\t\x12\x15\n\raircraftModel\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65pCity\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x65pCode\x18\x05 \x01(\t\x12\x0f\n\x07\x61rrCity\x18\x06 \x01(\t\x12\x0f\n\x07\x61rrCode\x18\x07 \x01(\t\x12\x15\n\rpassengerName\x18\x08 \x01(\t\x12\x12\n\npassportNo\x18\t \x01(\t\x12\x12\n\nflightDate\x18\n \x01(\t2\x8d\x02\n\rFlightService\x12L\n\x0cGetPublicKey\x12\x17.org.example.grpc.Empty\x1a#.org.example.grpc.PublicKeyResponse\x12V\n\rSetSessionKey\x12#.org.example.grpc.SessionKeyRequest\x1a .org.example.grpc.StatusResponse\x12V\n\rStreamFlights\x12!.org.example.grpc.EncryptedPacket\x1a .org.example.grpc.StatusResponse(\x01\x42\x14\n\x10org.example.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020org.example.grpcP\001'
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_PUBLICKEYRESPONSE']._serialized_start=44
  _globals['_PUBLICKEYRESPONSE']._serialized_end=79
  _globals['_SESSIONKEYREQUEST']._serialized_start=81
  _globals['_SESSIONKEYREQUEST']._serialized_end=120
  _globals['_ENCRYPTEDPACKET']._serialized_start=122
  _globals['_ENCRYPTEDPACKET']._serialized_end=174
  _globals['_STATUSRESPONSE']._serialized_start=176
  _globals['_STATUSRESPONSE']._serialized_end=226
  _globals['_FLIGHTDATA']._serialized_start=229
  _globals['_FLIGHTDATA']._serialized_end=434
  _globals['_FLIGHTSERVICE']._serialized_start=437
  _globals['_FLIGHTSERVICE']._serialized_end=706
# @@protoc_insertion_point(module_scope)
