# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlightServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPublicKey = channel.unary_unary(
                '/org.example.grpc.FlightService/GetPublicKey',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.PublicKeyResponse.FromString,
                _registered_method=True)
        self.SetSessionKey = channel.unary_unary(
                '/org.example.grpc.FlightService/SetSessionKey',
                request_serializer=service__pb2.SessionKeyRequest.SerializeToString,
                response_deserializer=service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StreamFlights = channel.stream_unary(
                '/org.example.grpc.FlightService/StreamFlights',
                request_serializer=service__pb2.EncryptedPacket.SerializeToString,
                response_deserializer=service__pb2.StatusResponse.FromString,
                _registered_method=True)


class FlightServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPublicKey(self, request, context):
        """1. Шаг: Клиент запрашивает публичный ключ сервера (PEM формат)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSessionKey(self, request, context):
        """2. Шаг: Клиент отправляет свой AES ключ, зашифрованный публичным ключом сервера
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFlights(self, request_iterator, context):
        """3. Шаг: Потоковая отправка данных (Client streaming)
        Клиент открывает 1 соединение и "льет" массив данных.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKey,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.PublicKeyResponse.SerializeToString,
            ),
            'SetSessionKey': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSessionKey,
                    request_deserializer=service__pb2.SessionKeyRequest.FromString,
                    response_serializer=service__pb2.StatusResponse.SerializeToString,
            ),
            'StreamFlights': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamFlights,
                    request_deserializer=service__pb2.EncryptedPacket.FromString,
                    response_serializer=service__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.example.grpc.FlightService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.example.grpc.FlightService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlightService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.example.grpc.FlightService/GetPublicKey',
            service__pb2.Empty.SerializeToString,
            service__pb2.PublicKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSessionKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.example.grpc.FlightService/SetSessionKey',
            service__pb2.SessionKeyRequest.SerializeToString,
            service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFlights(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/org.example.grpc.FlightService/StreamFlights',
            service__pb2.EncryptedPacket.SerializeToString,
            service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
